### ISSUE TITLE
The index.html is deleted when this module is executed?

### ISSUE THREAD

**Issue by timbuktu031** [bugsounet/MMM-AssistantMk2#415]
Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/index.html'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at /home/pi/MagicMirror/js/server.js:71:17
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:112:3)

이런 에러나고 검정색  화면만 출력됩니다. 
Magic mirror 정상 설치 되었고 
Hotword 모듈도 정상 동작하는데 
assistant 모듈 설치하고 나면 제대로 동작하지 않습니다. 
설치 단계에서 post-install 도 해줘야 하는것 맞은가요? 
electron 리빌더 다 해주는 것 맞나요? 이것과 무슨 관련이 있는것 같기도 하고 ... 
몇번 해도 마찬가지인데 모듈 설치하고 처음 설치시에는 제대로 화면이 뜹니다. 
그런데 magicmirror를 다시 끄고 켜면 에러 납니다. 

다시 보니 처음에 있었던 index.html 파일이 삭제 되어 버리네요.
모듈 설치하고 npm run start 해서 매직미러 재시작 하는 순간 index.html파일을 삭제해 버립니다. 
따로 복사해 놓았던 index.html 파일을 다시 복사해 넣어 주고 npm run start 하면 정상적으로 
화면이 출력됩니다. 무슨 일이죠?

결국에는 위 에러는 index.html  파일이 없어서 생기는 에러 같습니다. 
왜 모듈이 실행 되면서  이 파일을 강제로 지우는 건지 모르겠습니다. 

도움 말씀 부탁드립니다.

**Comment by PineMaster** [comment]
Hello, I have also encountered this issue :(

**Comment by timbuktu031** [comment]
> Hello, I have also encountered this issue :(

Yes. It seems that something is deleting the index.html file.
