### ISSUE TITLE
MM Index.html is despised and errors by run

### ISSUE THREAD

**Issue by aqildah** [bugsounet/MMM-AssistantMk2#416]
Hi, I have the latest Raspbian (Release date: 2020-05-27) which is now available and the Raspberry 4, 32 G sd and 2 G memory.
several times I installed the MM (MagicMirror) with or without auto install. no problem and working creat and fine.
I only install the MMM-AssistantMk2 to work together with MMM-Hotword but unfortunately after two weeks I was unsuccessful. audio and speaker are ok.
 I get no error in instllation and config. testing start with AssistandMK2 which with the "node auth_and_test.js" also have connection to the google assistant services and have no problem.
 But when I use the MM and de config file to present on MM in config with base:
{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    useWelcomeMessage: "brief today"
  }
},
nfortunately I get a lot of errors. i know that making app on google and registering of device is now different but i had no problem there. every time I do MM run (with or without pm2) and MK2 in the config file:
1- the index.html page of the / home / pi / MagicMirror will despised.
2- I get this error: [2020-05-29 19:52:12.536] [LOG]    [AMK2] assistant ready
[2020-05-29 19:52:12.550] [LOG]    [AMK2] Conversation starts.
[2020-05-29 19:52:12.598] [LOG]    Whoops! There was an uncaught exception...
[2020-05-29 19:52:12.599] [ERROR]  { [Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/1590774732550.mp3']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/1590774732550.mp3' }
[2020-05-29 19:52:12.600] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-05-29 19:52:12.602] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-05-29 19:52:12.619] [LOG]    [AMK2] Recorder Error: arecord has exited with error code 1.

Enable debugging with the environment variable DEBUG=record.
[2020-05-29 19:52:13.019] [LOG]    [AMK2] Assistant Text Response: 
[2020-05-29 19:52:42.885] [ERROR]  [AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 14,
  metadata:
   Metadata { _internal_repr: { 'content-disposition': [Array] }, flags: 0 },
  details: 'Service unavailable.' }

what will be the reason . i have the same problem in 2 or 3 weeks and I can resolve it!?
thanks for your help!

**Comment by sudoreddyman** [comment]
I have the same issue. I'm not sure what the issue is either. 

I'm wondering if it is worthwhile going back to MMM-AssistantMk2 V2, but I am not sure how to install an older version of a module.

**Comment by PineMaster** [comment]
@sudoreddyman #415 is also having the same issue :(
